### ISSUE TITLE
'download all', 'starred' and rate limiting.

### ISSUE THREAD

**Issue by bjohas** [delight-im/exportify#3]
Hello again,

The rate limiting causes some problems. The 'starred' list would naturally be large, and so 'export all' gets stuck on 'starred' unless you have a light use Spotify account. However, sooner or later, the rate limiting will kick in.

I had a quick look in the Spotify dev docs, but couldn't see a rate limit - what is it?

Would it be possible to iterate over playlists, and download one by one, rather than trying to zip them all? Even if the exporter then ran for a day, at the end you'd have your playlists. Or is this doomed somehow?

**Comment by ocram** [comment]
Spotify intentionally left out much of the detail in the documentation on rate limits. They want you to rely on the `Retry-After` HTTP response header instead and put in place *dynamic* limits. See [here](https://github.com/spotify/web-api/issues/589), [here](https://github.com/spotify/web-api/issues/326) and [here](https://github.com/spotify/web-api/issues/116).

If you have forked the code anyway, why not add some short times of [“sleep”](https://stackoverflow.com/questions/951021/what-is-the-javascript-version-of-sleep) between individual API calls, or at least batches of those?

By the way, you are probably referring to “saved tracks” or your “library”, which is the successor to the old “starred tracks” feature, right?

How many tracks do you actually have in your library? 5,000? 10,000?

Instead of downloading all playlists at once as a ZIP, you can just download the individual playlists from the list.

**Comment by bjohas** [comment]
Thanks!

By "starred" I meant the first library that comes up in the list. Not sure what it refers to, but I guess it's saved tracks now? I'm not sure whether it's still possible to get the old starred tracks somehow. I increased the track number to 10,000 before I gave up, so I have more than 10,000 saved tracks it seems.

I have about 800 playlists and would like to back these up programmatically before I tidy up. 

So if a short delay is ok, like a couple of seconds, then I can do that, and get the zip. But if it needs say 10 secs then I'd want to download files as I go, to make sure it's working.

Is the timeout also going to be an issue for long playlists? Given that the timeout seems to happen over the starred list, I assume this is the case? I have some "all albums of artist X" which can be say 2000 tracks....

**Comment by ocram** [comment]
Well, the list of available playlists shows a name for each entry, and if it says “Saved”, this is indeed the newer “Saved Tracks”, “Your Music” or “Library” feature.

The old “Starred Tracks” feature had been undocumented and was apparently removed by Spotify in 2018, perhaps around May. That was also the cause for [this other issue](https://github.com/delight-im/exportify/issues/1).

So I don’t think there’s any way left to access that obsolete feature and its tracks. But Spotify surely has migrated the tracks to some other place for its users, right? They certainly didn’t just remove them without any replacement.

The number next to “Saved” is not actually the real number of tracks in that playlist but just the number you supplied as the library size manually. Sorry! In order to find out how many tracks you actually have, you’d need to keep that limit at 10,000 and download the list and then check how many lines or records are in that file.

Spotify has a limit of 10,000 songs and/or albums in your library, as far as we know:

 * https://www.reddit.com/r/spotify/comments/7qpguo/10000_song_library_limit/
 * https://community.spotify.com/t5/Live-Ideas/Your-Music-Increase-maximum-Songs-allowed-in-Your-Music/idi-p/733759
 * https://community.spotify.com/t5/Accounts/Library-Song-Limit/td-p/1664935

You certainly seem to be on the upper end of the spectrum with your library and playlist sizes, but this tool should still work, of course.

If you inserted the “sleep” time at the beginning of [`apiCall`](https://github.com/delight-im/exportify/blob/88e158db4fa90ed51189ffe79e426ee72396c8dc/exportify.js#L20), you could insert a break between any two API calls. Perhaps use a counter or a random number to limit this to every fifth API call, or something like that. With the duration, you’d obviously have to experiment. Why not start with one second?

Long playlists require multiple API calls because Spotify does limit the number of returned tracks. So a large library or playlist will require dozens of requests.

We also have https://github.com/delight-im/Tools-for-Spotify – which is more advanced, has more additional features, but requires PHP to be installed and a configuration file to be set up. So it could be the right tool to back up (or de-duplicate) a large playlist, but not (yet) the right tool to back up 800 playlists at once.

**Comment by bjohas** [comment]
That's really helpful! I'll try this out and see!

**Comment by bjohas** [comment]
Hmmm - so I've tried this for a bit, but I guess I'm not quite versed enough in js to figure out the sleep. I guess a promise would be the way to do it? Any tips?! :)

**Comment by ocram** [comment]
Apart from `Promise` and `async`/`await`, you can use a synchronous implementation that will block and thus may make the page appear to hang or freeze. Such a solution is not ready for production, but just on your own machine, for temporary experiments, this should be fine:

```javascript
function sleep(ms) {
	var start = Date.now();
	while (Date.now() < (start + ms)) {}
}
```

Then, anywhere you like, insert `sleep(1000);` for a one-second sleep.

**Comment by bjohas** [comment]
Fair enough - many thanks. I had put that in, it means the fan on my laptop comes on as Chrome tries to compare the date as quickly as possible, which then makes tab unresponsive (and nicely warms up my laptop) :) But yes, it seems to work. One and two secs didn't work, so I'm trying three now. Writing the uuid to the console, so I know it's still running.

**Comment by ocram** [comment]
Glad to hear that it seems to work. As I said, this solution is not ready for production, is wildly inefficient, and may make the page unresponsive. But for development, debugging and local tests, this shouldn’t matter. You know the page will eventually become responsive again.

Adding a statement to print the current status to the console is a great idea. Apart from proving that the script is still working, it may further slow down the script, which is what we want here, depending on where you insert it. If you really need to make this more efficient, you may need the `async` solution.

**Comment by bjohas** [comment]
So here's an update. I've tried various ways of just inserting a fixed delay, e.g. introducing a 2 sec sleep between calls, and then also a sleep on every 20th call (10sec) and 100th call (60 sec). However, while that seems to have worked, I guess I ran into an auth code expiry. Hard to say, as I didn't watch it all the time :)

So I then decided to look at the 'Retry-After' header.  Basically, I can make 1124 requests without throttling, but then get a 'Retry-After' (in seconds) at every request. The Retry-After is typically 1 second, but can be longer, e.g. 7 seconds. After the 'Retry-After', I just wait, and then fetch again. That seems to work so far. Will post code later if it actually works.

**Comment by bjohas** [comment]
That didn't really work :( It ran for several hours, but it's hard to tell how far it is... time was about 10 secs between retries. 

Option 1: Just get the first 1024, then wait for a bit, get the next 1024 (so requires a restart-from or similar...)

Option 2: It'll be more controllable from the command line. Do you have an example how you would use the php tool to download the whole library?

Thanks!

**Comment by ocram** [comment]
Thanks for the updates!

It’s really unfortunate that this didn’t seem to work, because all this sounded so good and promising. Especially your approach of sleeping not randomly but in accordance with the `Retry-After` header sounded like a proper solution.

The server-side tools are more advanced, but after all, they cannot do more than sleep either if Spotify throttles the requests. So as sleeping seemed to have worked in JavaScript, I’m not sure if the server-side tools will have any advantages. It’s just that sleeping is easier to do and more “natural” there because the server and language are synchronous.

Anyway, the server-side tools have detailed documentation available [here](https://github.com/delight-im/Tools-for-Spotify), and all you need is PHP on your local machine (or on some cheap web server). PHP has a [built-in web server](https://www.php.net/manual/en/features.commandline.webserver.php), so you may not need anything else on your local machine. If you can serve files on `localhost` (or any other server) and access the files from the tools in your web browser, your setup is done. Now all you need is write configuration files for your tasks as needed (see documentation).

**Comment by bjohas** [comment]
Every time I authenticate, i get another 1124 requests. However (as above) then the time-delays get tricky (though it's also possible I messed something up with the asynchronous calls).

But, one possibility would thus be to re-authenticate. Get all my playlists. Do 1124 requests. Re-authenticate, continue where I left off.

**Comment by ocram** [comment]
That makes sense. I still believe this can be solved equally well with both tools, the client-side version here and the server-side tools referenced above.

When `csvData` returns its results for a single playlist, you know that this playlist has been completed. So why not add it to a list in `window.localStorage` at this point, and during the next run (after re-authentication) skip all the playlists from that list?

**Comment by pavelkomarov** [comment]
@bjohas @ocram Without ever seeing this thread I had the same idea. My `apiCall` function takes a `delay` parameter so I can space out the calls intentionally. https://github.com/pavelkomarov/exportify/blob/master/exportify.js . This was a major issue for me, as my whole intention was to add as many interesting columns as possible for [analysis](https://github.com/pavelkomarov/exportify/blob/master/taste_analysis.ipynb), which necessitated querying for artists and track audio features (two additional waves of traffic).

I've found experimentally that about 10 calls a second doesn't cause any failures. 15 did. My Export Group button exports in series so it takes longer but has no danger of hitting the rate limit. Right now that just gets the 20 listed on the current page. For the (insane) case of 800+ playlists (seriously what r u doing?), I would [need to reimplement](https://github.com/pavelkomarov/exportify/issues/9) querying for the list of all playlists before passing them to the loop in my `ZipExporter`.

[live version](https://pavelkomarov.com/exportify/app.html)
