### ISSUE TITLE
Tracks count from the web dashboard doesn't match the CSV fields

### ISSUE THREAD

**Issue by maxiride** [delight-im/exportify#4]
I wanted to download the _starred_ CSV and from the web dashboard of Exportify I see 2500 tracks.
https://i.imgur.com/iVpQnnB.png

However, after downloading the CSV the files has "only" 566 tracks in it.

I can confirm that the CSV is the **right** one as I doublechecked within Spotify my starred tracks so no data is missing but I supposed to report this incongruence anyway 😊

**Comment by bjohas** [comment]
Hi there,

See: https://github.com/delight-im/exportify/issues/3

> The number next to “Saved” is not actually the real number of tracks in that playlist but just the number you supplied as the library size manually. Sorry! In order to find out how many tracks you actually have, you’d need to keep that limit at 10,000 and download the list and then check how many lines or records are in that file.

I'm not sure why it's like that, but it's a "known thing".

**Comment by ocram** [comment]
@bjohas Thanks for your help!

@Maxiride If your CSV file actually has fewer lines than 2,501 (including one header row), everything is fine and the export should be complete. Only if there’s a full 2,501 rows in your output file, you need to increase the limit as documented in the README. All this only affects the “Saved” list, not any other playlist.

The reason for this behavior is that, while we can retrieve the number of tracks in a playlist before actually fetching those tracks by iterating over the individual “pages”, there’s no such information for the “Saved” list. So we cannot know in advance how many entries there are in “Saved”. As a workaround, we assume 2,500 tracks, which is a limit that can be increased (see above).

When it comes to actually fetching the tracks, we could ignore that limit and iterate until the last “page” has been reached. But this would require additional code changes, which we wanted to avoid to stay close to the original version.

In order to avoid further confusion, the (usually wrong) estimate for the number of tracks in “Saved” is [now](https://github.com/delight-im/exportify/commit/17cd4fa093bfc5c4523a72ef13cd6dfb6a29fb28) not shown anymore.

Our other (related) project, [“Tools for Spotify”](https://github.com/delight-im/Tools-for-Spotify), does not have any such limitation.
